name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'  # sadece v1.0.0 gibi taglerde çalışır

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Repo checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # .NET setup
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Run tests (opsiyonel)
      - name: Test
        run: dotnet test --no-build --verbosity normal

      # Extract version from tag
      - name: Set version from tag
        id: get_version
        run: |
          echo "##[set-output name=version]${GITHUB_REF##*/v}"

      # Pack NuGet package
      - name: Pack NuGet package
        run: dotnet pack ./Resultify.Core/Resultify.Core.csproj -c Release --no-build -p:PackageVersion=${{ steps.get_version.outputs.version }} -o ./nupkg

      # Push to NuGet
      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json